version: '3'
services:
  cram-vrb-lab:
    image: cram-vrb-lab:main
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    user: root
    working_dir: /home/jovyan/vrb-cable-demo
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0 --ServerApp.default_url=/lab/tree/notebooks/daisy_cable_demo.ipynb
    ports:
      - 8888:8888
      - 6080:6080
    environment:
      - REPO_DIR=/home/jovyan/vrb-cable-demo
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ACCEPT_EULA=YES
      - PRIVACY_CONSENT=YES
      - OMNI_KIT_ACCEPT_EULA=YES
      - OMNI_KIT_ALLOW_ROOT=1
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
